version: '3'
services:
  dbsql:
    image: postgres:13
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password1
      POSTGRES_DB: shopcrm
    ports:
      - 5432:5432
    networks:
      - backend
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistent storage

  app:
    container_name: store-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    depends_on: 
      - dbsql
    networks:
      - backend
    environment:
      EMAIL_SECRET: ${EMAIL_SECRET}
      EMAIL_USER: ${EMAIL_USER}
      # connect to the PostgreSQL container by its service name, not localhost
      DATABASE_HOST: dbsql
      DATABASE_USER: "postgres"
      DATABASE_PASSWORD: password1
      DATABASE_NAME: "shopcrm"
      FRONTEND_URL: ${FRONTEND_URL}
      DATABASE_ENABLE_SYNC: true
      DATABASE_ENABLE_LOGGING: false
      DATABASE_CONNECT_RETRY_COUNT: 4

volumes:
  postgres_data:

networks:
  backend:
    external: true