version: '3'
services:
  dbsql:
    image: postgres:alpine3.21
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password1
      POSTGRES_DB: shopcrm
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistent storage

  app:
    container_name: store-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:4000
    environment:
      EMAIL_SECRET: "czmpfrduvibtunoc"
      DATABASE_HOST: localhost
      # DATABASE_HOST: "dpg-csp6ufd6l47c73a19s60-a"
      DATABASE_USER: "postgres"
      DATABASE_PASSWORD: "password1"
      DATABASE_NAME: "shopcrm"

volumes:
  postgres_data:
  
    # depends_on:
      # - dbsql
    #   DATABASE_HOST: localhost
      # STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
    #   Client_URL: https://buy-tylerjusfly.vercel.app
    #   COINBASE_API_KEY: ${COINBASE_KEY}
    #  PORT: 8081
    #  STRIPE_PUBLISHABLE_KEY: ${STRIPE_PUBLISHABLE_KEY}
    #  SERVICE_TAGS: prod
    #  SERVICE_NAME: nodeapiservice 