version: '3'
services:
  dbsql:
    container_name: postgres_container
    image: postgres
    # restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tylerjusfly1996
      POSTGRES_DB: shopcrm
    ports:
      - 5432:5432
  #   expose:
  #     - 5432

  app:
    container_name: store-backend
    image: store-backendv1
    ports:
      - 8000:4000
    environment:
    #   DATABASE_HOST: localhost
      # DATABASE_USER: "postgres"
      # DATABASE_PASSWORD: "tylerjusfly1996"
      # DATABASE_NAME: shopcrm
    #   STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
    #   Client_URL: https://buy-tylerjusfly.vercel.app
    #   COINBASE_API_KEY: ${COINBASE_KEY}
    # depends_on:
    #         - dbsql
    #  SQL_PORT: 3306
    #  PORT: 8081
    #  STRIPE_PUBLISHABLE_KEY: ${STRIPE_PUBLISHABLE_KEY}
    #  SERVICE_TAGS: prod
    #  SERVICE_NAME: nodeapiservice 